server:
  port: 8080
spring:
  datasource:
    username: root
    password: 243698
    url: jdbc:mysql://localhost:3306/mymall?rewirteBatchedStatements=true&serverTimezone=GMT%2B8


mybatis:
  mapper-locations:
    -classpath:mapper/*.xml
    -classpath*:com/**/mapper/*/xml