server:
  port: 8080

spring:
  datasource:
    username: root
    password: 243698
    #url: jdbc:mysql://localhost:3306/mymall
    url: jdbc:mysql://localhost:3306/mymall?rewirteBatchedStatements=true&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver




jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

mybatis:
  mapper-locations:
    -classpath:mapper/*.xml
    -classpath*:com/**/mapper/*/xml


